  proxy:
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
  # db:
  #   image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
        - VIRTUAL_HOST=devise.dev
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - database:database.dev

# web:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/myapp
#       # - './env/tmp/bundler':"./bundler"
#       # - './env/tmp/tmp': "./tmp"
#       # - './env/tmp/log': "./log"
#       # - './env/tmp/.bundle': "./.bundle"
#     ports:
#       - "3000:3000"
#     links:
#         - database:database.dev
    # links:
    #   - db

  database:
    image: freshbooks/percona:5.5
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=myapp_development
        - VIRTUAL_HOST=database.dev
    volumes:
        # - 101pet-mysql:/var/lib/mysql
        - ./my.cnf:/etc/mysql/my.cnf
    ports:
        - "3306:3306"
