# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfabd25b98019a6651d8c702225546608cdcd8aa3e9761f4fb6cb1ecb5042c2e9140afa3e192c5a1b3cd6dc8149cc46904309218fb298143f17308e84fd52fd5

test:
  secret_key_base: d3741067b6facc829615c48ea409117b5cb8f713c4a2da21c59517e7d57f64c9dc734040b54ee7637e38006f8ebe92f60579f92f0c9cb4bc42226dac693698aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
