# db:
#     image: postgres

web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
        - database:database.dev
    # links:
    #   - db

database:
    image: freshbooks/percona:5.5
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=myapp_development
        - VIRTUAL_HOST=database.dev
    # volumes:
    #     - 101pet-mysql:/var/lib/mysql
    ports:
        - "3306:3306"
